root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/bin ."
  bin = "./tmp/bin"
  delay = 500
  exclude_dir = ["3rdpartylibs", "dist"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]
